name: Terraform Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: | 
        dotnet restore ./Lambdas/AuthLambda
        dotnet restore ./Lambdas/CreateUserLambda
        dotnet restore ./Lambdas/GetUserInfoLambda

    - name: Build
      run: |
        dotnet build ./Lambdas/AuthLambda --no-restore
        dotnet build ./Lambdas/CreateUserLambda --no-restore
        dotnet build ./Lambdas/GetUserInfoLambda --no-restore

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        tf_version: 1.0.0

    - name: Terraform init
      run: |
        cd terraform
        terraform init

    - name: Terraform plan
      run: |
        cd terraform
        terraform plan
